### ISSUE TITLE
最新版到14了，也有类似的修改版，这个隐私增强还有更新的可能吗？

### ISSUE THREAD

**Issue by WtXeLd** [LeslieYon/Geek_SougouIME#2]
因为 10.0 UI 也比较旧了，房子啊 Win 11 上有点怪，现在新版有了深色模式，UI 整体也比较新，不知道有没有可能能更新一版~

修改版的地址
https://www.123pan.com/s/A6cA-WlAJh

**Comment by LeslieYon** [comment]
有时间一定安排
